name: test
on:
  push:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest
    outputs:
      test-env: ${{ steps.set-env.outputs.test-env }}
    steps:
      - uses: actions/checkout@v4
        name: checkout
        with:
          fetch-depth: 2

      - name: Check changed files
        id: set-env
        run: |
          echo "Checking changed files..."
          if git diff HEAD^ --name-only | grep -q 'src/test.yaml'; then
            echo "test-env=test" >> $GITHUB_OUTPUT
          else
            echo "test-env=none" >> $GITHUB_OUTPUT
          fi

      - name: echo test-env
        shell: bash
        run: echo ${{ needs.check_files.outputs.test-env }}
